[project]
name = "ai-builders-week-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.48.1",
    "yfinance>=0.2.65",
]
